# Generated by Django 4.1 on 2023-08-14 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_remail', models.EmailField(max_length=128, unique=True, verbose_name='생성 주소')),
                ('address_category', models.CharField(max_length=32, unique=True, verbose_name='생성 주소 카테고리')),
            ],
            options={
                'verbose_name': 'remail 주소',
                'verbose_name_plural': 'remail 주소',
                'db_table': 'address',
            },
        ),
    ]
