# Generated by Django 4.1 on 2023-08-15 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remailbox', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='List_user',
        ),
    ]
